'use client'

import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Hero from '@/components/hero'
import Nav from '@/components/nav'
import Feature from '@/components/feature'
import Footer from '@/components/footer'
// import InputGroup from '@/components/input'
// pages/index.tsx
// import prisma from '../../lib/prisma';
import CreateUser from '@/components/createUser'
import { useState, useEffect } from 'react'
import { Auth } from '@supabase/auth-ui-react'
import { ThemeSupa } from '@supabase/auth-ui-shared'
import { createClient } from '@supabase/supabase-js'
import { useSessionContext, useSupabaseClient, useUser } from '@supabase/auth-helpers-react'
// import { createServerSupabaseClient } from '@supabase/auth-helpers-nextjs'
// import { supabase } from '../lib/api'
// import Auth from '../components/Auth'
import dynamic from 'next/dynamic'
import useSWR from 'swr'
 

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // console.log('user from ssr', user)
  const supabase = useSupabaseClient()
  const user = useUser()

  const { data, error } = useSWR('fetchAllItems', fetchAllItems)

      return (
        <>
          <Head>
            <title>UpTap</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main>
            <Nav />
            <Hero /> 
            <Feature /> 
            <Footer />
          </main>
        </>
      )
    }



